### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by AsixJin** [rkaradas/MaPerWiki#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [MaPerWiki](https://github.com/rkaradas/MaPerWiki) package 0.1.20

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of null

```
At C:\Users\AsixJin\.atom\packages\MaPerWiki\lib\Models\LinkCheckerModel.js:247

TypeError: Cannot read property 'length' of null
    at LinkCheckerModel.findAllHeaders (/packages/MaPerWiki/lib/Models/LinkCheckerModel.js:247:28)
    at /packages/MaPerWiki/lib/Models/LinkCheckerModel.js:157:44
    at Workspace.scan (/app.asar/src/workspace.js:1280:11)
    at LinkCheckerModel.findReferenceInfiles (/packages/MaPerWiki/lib/Models/LinkCheckerModel.js:152:37)
    at /packages/MaPerWiki/lib/Models/LinkCheckerModel.js:57:22
```

### Commands

```
     -3:16.3.0 spell-check:correct-misspelling-5 (span.syntax--source.syntax--gfm)
 42x -3:08.9.0 core:backspace (input.hidden-input)
     -1:31.1.0 markdown-writer:insert-new-line (input.hidden-input)
     -1:31.1.0 editor:newline (input.hidden-input)
     -1:30.9.0 markdown-writer:insert-new-line (input.hidden-input)
     -1:30.9.0 editor:newline (input.hidden-input)
  2x -1:27.1.0 core:backspace (input.hidden-input)
     -1:25.9.0 markdown-writer:insert-new-line (input.hidden-input)
     -1:25.9.0 editor:newline (input.hidden-input)
     -0:50.5.0 core:move-left (input.hidden-input)
     -0:50.1.0 core:backspace (input.hidden-input)
     -0:36.8.0 core:select-all (input.hidden-input)
     -0:35.9.0 core:copy (input.hidden-input)
     -0:28.6.0 tree-view:paste (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:26.9.0 core:paste (input.hidden-input)
 12x -0:25.1.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 1.4.0 
MaPerWiki 0.1.20 
markdown-preview-enhanced 0.12.0 
markdown-writer 2.6.4 
tool-bar 1.1.0 
tool-bar-markdown-writer 0.2.0 
```

**Comment by rkaradas** [comment]
Hi @AsixJin,

could you provide your markdown file(s). 
Thanks.

**Comment by AsixJin** [comment]
All of them that I'm using with MaPerWiki?

**Comment by rkaradas** [comment]
If you can pinpoint the file where this happens then the file would be enough. 
I think I know the problem, but I need the file(s) to reproduce the error and check the possible fix.
If you can't provide the files it may take longer to fix the issue.
Thanks.

**Comment by AsixJin** [comment]
@rkaradas 
Finally got the error again while editing this file here...IT happened right as I was adding the bracket & parathesis for the page link.

https://drive.google.com/open?id=0B5C4s9oTHqWgSGtia2h1dUFMVk0

**Comment by rkaradas** [comment]
@AsixJin 
Thanks for providing me the markdown file. 
I'll fix it this weekend and publish a new version. 
You could disable the "autocheck broken WikiLinks" setting for now (see screenshot below). 
The issue occurs if you have an empty link []() and check for broken WikiLinks. So if you disable the autocheck feature and don't check for broken WikiLinks while you have empty links, the problem shouldn't occur. Like I said it's just a workaround for now so you don't get bothered with the exception.
![](https://github.com/rkaradas/MaPerWiki/blob/master/images/settings-linkchecker.png?raw=true)

**Comment by rkaradas** [comment]
@AsixJin 
It should be fixed now. 
Can you confirm?

**Comment by AsixJin** [comment]
It seems to be fixed now! Thanks!

**Comment by rkaradas** [comment]
Glad to hear that. If you have any ideas to improve the package, feel free to request a feature
