### ISSUE TITLE
Links wrongly reported as broken when pointing to a file.

### ISSUE THREAD

**Issue by PabloRomanH** [rkaradas/MaPerWiki#4]
When I make links that point to a PDF file, they work in the preview, but they are reported as broken.

For example:
`[Original Paper](/research/paper/some_paper.pdf)`

**Comment by rkaradas** [comment]
Hi @PabloRomanH,

please remove the first slash and try again. The first slash is handled as the root entry point of your file system. 

Your example should look like this:
`[Original Paper](research/paper/some_paper.pdf)`

**Comment by PabloRomanH** [comment]
Oh, it does work for .md files though. Links to .md files are considered to be relative to the root of the project. It works both in the broken link verifier and in the html renderer. Is that an unintended feature? If that's the case then I'll switch to using relative paths.

**Comment by rkaradas** [comment]
Maybe I'll change it in the future, but for now it's best to use relative paths.
